### ISSUE TITLE
Close Tabs not working

### ISSUE THREAD

**Issue by sibeshkar** [mayahq/maya-red-browser-automation#12]
close tabs not working 

```
(node:7728) UnhandledPromiseRejectionWarning: ReferenceError: node is not defined
    at /Users/sibeshkar/Maya/packages/maya-red-browser-automation/src/utils/getValue.js:11:11
    at Object.evaluateNodeProperty (/usr/local/lib/node_modules/node-red/node_modules/@node-red/util/lib/util.js:519:17)
    at /Users/sibeshkar/Maya/packages/maya-red-browser-automation/src/utils/getValue.js:6:16
    at new Promise (<anonymous>)
    at getValue (/Users/sibeshkar/Maya/packages/maya-red-browser-automation/src/utils/getValue.js:2:10)
    at MayaBrowserQuery._inputCallback (/Users/sibeshkar/Maya/packages/maya-red-browser-automation/src/nodes/mayaBrowserQuery/mayaBrowserQuery.js:19:25)
    at MayaBrowserQuery.Node._emitInput (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:456:21)
(node:7728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

Try this flow : 

[flows.txt](https://github.com/mayahq/maya-red-browser-automation/files/6563168/flows.txt)

**Comment by sibeshkar** [comment]
Fixed.
