### ISSUE TITLE
YT SKILL PACK: Find Tab Not working

### ISSUE THREAD

**Issue by sagewhocodes** [mayahq/maya-red-browser-automation#15]
```toggling command bar from backend open
(node:15454) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at FindTab.onMessage (/home/atlas/.maya/packages/github.com/mayahq/maya-red-browser-automation/src/nodes/mayaBrowserFindTab/mayaBrowserFindTab.schema.js:34:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async nodefn._inputCallback (/home/atlas/.maya/packages/github.com/mayahq/maya-red-browser-automation/node_modules/@mayahq/module-sdk/src/node.js:106:28)
(node:15454) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
toggleCommand { params: {}, paths: {} }
toggling command bar from backend close
toggling command bar from backend open
(node:15454) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at FindTab.onMessage (/home/atlas/.maya/packages/github.com/mayahq/maya-red-browser-automation/src/nodes/mayaBrowserFindTab/mayaBrowserFindTab.schema.js:34:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async nodefn._inputCallback (/home/atlas/.maya/packages/github.com/mayahq/maya-red-browser-automation/node_modules/@mayahq/module-sdk/src/node.js:106:28)
(node:15454) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
toggleCommand { params: {}, paths: {} }
toggling command bar from backend close
toggling command bar from backend open
(node:15454) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at FindTab.onMessage (/home/atlas/.maya/packages/github.com/mayahq/maya-red-browser-automation/src/nodes/mayaBrowserFindTab/mayaBrowserFindTab.schema.js:34:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async nodefn._inputCallback (/home/atlas/.maya/packages/github.com/mayahq/maya-red-browser-automation/node_modules/@mayahq/module-sdk/src/node.js:106:28)
(node:15454) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
toggleCommand { params: {}, paths: {} }
toggling command bar from backend close
toggling command bar from backend open
(node:15454) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at FindTab.onMessage (/home/atlas/.maya/packages/github.com/mayahq/maya-red-browser-automation/src/nodes/mayaBrowserFindTab/mayaBrowserFindTab.schema.js:34:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async nodefn._inputCallback (/home/atlas/.maya/packages/github.com/mayahq/maya-red-browser-automation/node_modules/@mayahq/module-sdk/src/node.js:106:28)
(node:15454) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)
toggleCommand { params: {}, paths: {} }
toggling command bar from backend close
```

**Comment by sibeshkar** [comment]
Update on this : This happened when the native messaging host was not being loaded.
